from db.relationships import OneToMany
from decorators.AutoGenerated import AutoGenerated
from decorators.Entity import Entity
from datetime import date


@Entity("books")
class Book():
    id: AutoGenerated(int)
    title: str
    author_id: int

@Entity("authors")
class Author():
    id: AutoGenerated(int)
    name: str
    birth_date: date
    death_date: date
    books: OneToMany(Book, "author_id", "id")


def main():
    author = Author()
    author.name = "John Doe"
    author.birth_date = date(1955, 1, 1)
    author.death_date = date(2000, 1, 1)

    book = Book()
    book.title = "The Lord of the Rings"

    author.books.add(book)

    book = Book()
    book.title = "The Hobbit"

    author.books.add(book)
    
    author.save()

    author.name = "Jane Doe"
    author.save()

    print([book.id for book in author.books.get()])

if __name__ == '__main__':
    main()