from db.relationships import OneToMany
from decorators.AutoGenerated import AutoGenerated
from decorators.Entity import Entity
from datetime import date
from schemas.Book import Book


@Entity("authors")
class Author():
    id: AutoGenerated(int)
    name: str
    birth_date: date
    death_date: date
    books: OneToMany(Book, "author_id", "id")