from decorators.AutoGenerated import AutoGenerated
from decorators.Entity import Entity
from datetime import date

@Entity("books")
class Book():
    id: AutoGenerated(int)
    title: str
    author_id: int
    number_of_pages: int
    publication_date: date